# Generated by Django 5.1.2 on 2024-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='laptops/', verbose_name='Image')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('storage', models.IntegerField(verbose_name='Storage')),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Screen size')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('warranty_period', models.DateField(verbose_name='Warranty period')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
