# Generated by Django 5.1.2 on 2024-11-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='laptops/', verbose_name='Image')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('color_ky', models.CharField(max_length=255, null=True, verbose_name='Color')),
                ('color_ru', models.CharField(max_length=255, null=True, verbose_name='Color')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('storage', models.IntegerField(verbose_name='Storage')),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Screen size')),
                ('stock', models.BooleanField(default=False)),
                ('total_rating', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop', verbose_name='Laptop')),
            ],
        ),
    ]
