# Generated by Django 5.1.2 on 2024-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='color_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='color_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='stock_ky',
            field=models.CharField(max_length=4, null=True, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='stock_ru',
            field=models.CharField(max_length=4, null=True, verbose_name='Stock'),
        ),
    ]
